Add check for base commit SHA

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -43,12 +43,12 @@ jobs:
           # Получаем хэши базовой и головной веток PR
           BASE_SHA=${{ github.event.pull_request.base.sha }}
           HEAD_SHA=${{ github.event.pull_request.head.sha }}
-          
+
           # Подсчитываем количество коммитов между базой и головой PR
           COMMIT_COUNT=$(git rev-list --count $BASE_SHA..$HEAD_SHA)
-          
+
           echo "Info: Number of commits in PR: $COMMIT_COUNT"
-          
+
           # Проверяем, что количество коммитов равно 2
           if [ "$COMMIT_COUNT" -ne 2 ]; then
             echo "Error: Commit count in PR is incorrect, excected 2 commits, got $COMMIT_COUNT"
@@ -63,16 +63,33 @@ jobs:
           # Получаем хэши базовой и головной веток PR
           BASE_SHA=${{ github.event.pull_request.base.sha }}
           HEAD_SHA=${{ github.event.pull_request.head.sha }}
-          
+
           # Подсчитываем количество изменённых файлов
           FILE_COUNT=$(git diff --name-only $BASE_SHA..$HEAD_SHA | wc -l)
-          
+
           echo "Info: Number of changed files in PR: $FILE_COUNT"
-          
+
           # Проверяем, что изменён ровно 1 файл
           if [ "$FILE_COUNT" -ne 1 ]; then
             echo "Error: Changed files count is incorrect, expected 1 changed file, got $FILE_COUNT"
             exit 1
           else
             echo "Success: Changed files count is correct"
+          fi
+
+      - name: Check base commit SHA
+        if: ${{ !cancelled() }}
+        run: |
+          # Заданный SHA, из которого должна быть создана ветка
+          EXPECTED_SHA="e29acfeee8b29ec6b18d3f4cfa0c1833293a14ec"
+
+          # SHA последнего коммита в ветке PR
+          HEAD_SHA=${{ github.event.pull_request.head.sha }}
+
+          # Проверяем, содержит ли история ветки PR ожидаемый SHA
+          if git merge-base --is-ancestor "$EXPECTED_SHA" "$HEAD_SHA"; then
+            echo "Success: PR branch is based on expected SHA"
+          else
+            echo "Error: PR branch is not based on expected SHA"
+            exit 1
           fi
